### ISSUE TITLE
String maps can't bet getted with &str

### ISSUE THREAD

**Issue by nappa85** [TylerBloom/CycleMap#3]
`CycleMap::get_(left|right)` has this signature:
```rust
pub fn get_left<Q>(&self, item: &Q) -> Option<&L>
where
    Q: Borrow<R>,
```

This means that the map key has to be borrowable as the passed key.

If I have a `CycleMap<String, String>` and try to do `.get_left(&"my_key")` it won't work, since `&str` doesn't implement `Borrow<String>` (removing the reference doesn't work too, since `str` isn't `Sized`).

`std::collection::HashMap::get` instead has this signature:
```rust
pub fn get<Q>(&self, k: &Q) -> Option<&V>
where
    K: Borrow<Q>,
    Q: Hash + Eq + ?Sized,
```

That is the exact opposite, and allows me to do `.get("my_key")` on a String keyed map.

`HashBrown` uses a similar approach, but with the `Equivalent` trait.

**Comment by TylerBloom** [comment]
Addressed in #4
